[package]
authors = ["dbr <dbr.onix@gmail.com>"]
edition = "2018"
name = "vidl"
version = "0.1.0"
[dependencies]
anyhow = "1"
attohttpc = "*"
chrono = "0.4"
clap = "*"
fern = "*"
log = "*"
serde = "*"
serde_derive = "*"
serde_json = "1.0"
threadpool = "*"
directories = "2.0.2"
rouille = "3"
tera = "1.0"
lazy_static = "*"

[patch.crates-io]
# Patch to newer version than the latest released 3.0.0, contains websocket CPU fix and poll_timeout
rouille = { git = 'https://github.com/tomaka/rouille', rev = 'e9692e1b19c8d25a742129a16bbe826c686ab274' }

[dev-dependencies]
mockito = "*"

[dependencies.rusqlite]
features = ["chrono"]
version = "0.21"
