[package]
authors = ["dbr <dbr.onix@gmail.com>"]
edition = "2018"
name = "ytdl"
version = "0.1.0"
[dependencies]
anyhow = "1"
attohttpc = "*"
chrono = "0.4"
clap = "*"
env_logger = "*"
fern = "*"
log = "*"
serde = "*"
serde_derive = "*"
serde_json = "1.0"
threadpool = "*"

[dependencies.rusqlite]
features = ["chrono"]
version = "0.21"
